version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/letsencrypt/live/sorakrit-b.tech:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - container1
      - container2
    networks:
      - webnet

  container1:
    build:
      context: ./Container1
    container_name: container1
    networks:
      - webnet

  container2:
    build:
      context: ./Container2
    container_name: container2
    networks:
      - webnet

networks:
  webnet:
